framework:
    messenger:
        failure_transport: failed

        transports:
            support_tech:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queue:
                        name: support_tech_queue
                    routing_key: 'support.tech.high'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            support_finance:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queue:
                        name: support_finance_queue
                    routing_key: 'support.finance.low'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            support_management:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queue:
                        name: support_management_queue
                    routing_key: 'support.management.*'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            support_fanout:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: support_fanout_exchange
                        type: fanout
                    queue:
                        name: support_logger_queue
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            support_fanout_telegram:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: support_fanout_exchange
                        type: fanout
                    queue:
                        name: support_telegram_queue
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: failed_exchange
                        type: direct
                    queue:
                        name: failed_messages_queue

        routing:
            'App\Message\SupportRequestMessage':
                - support_tech
                - support_finance
                - support_management
                - support_fanout
                - support_fanout_telegram
