framework:
    messenger:
        transports:
            support_tech:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_TECH)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queues:
                        support_tech_queue:
                            binding_keys: [ 'support.tech.*' ]

            support_finance:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_FINANCE)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queues:
                        support_finance_queue:
                            binding_keys: [ 'support.finance.*' ]

            support_management:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_MANAGEMENT)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queues:
                        support_management_queue:
                            binding_keys: [ 'support.management.*' ]

            support_fanout:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_FANOUT)%'
                options:
                    exchange:
                        name: support_fanout_exchange
                        type: fanout
                    queues:
                        support_fanout_queue: ~

            support_fanout_telegram:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_FANOUT_TELEGRAM)%'
                options:
                    exchange:
                        name: support_fanout_exchange
                        type: fanout
                    queues:
                        support_fanout_telegram_queue: ~

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'
                options:
                    exchange:
                        name: failed_exchange
                        type: direct
                    queues:
                        failed_queue: ~

        routing:
            'App\Message\SupportRequestMessage':
                - support_tech
                - support_finance
                - support_management
                - support_fanout
                - support_fanout_telegram
