framework:
    messenger:
        transports:
            support_tech:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_TECH)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queues:
                        support_tech_queue:
                            binding_keys: ['support.tech.high']
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                failure_transport: failed

            support_finance:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_FINANCE)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queues:
                        support_finance_queue:
                            binding_keys: ['support.finance.low']
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                failure_transport: failed

            support_management:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_MANAGEMENT)%'
                options:
                    exchange:
                        name: support_topic_exchange
                        type: topic
                    queues:
                        support_management_queue:
                            binding_keys: ['support.management.*']
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                failure_transport: failed

            support_fanout:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SUPPORT_FANOUT)%'
                options:
                    exchange:
                        name: support_fanout_exchange
                        type: fanout
                    queues:
                        support_fanout_queue: ~

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'
                options:
                    exchange:
                        name: failed_exchange
                        type: direct
                    queues:
                        failed_queue: ~

        routing:
#            Можно убрать, потому что написал отдельный класс, который кидает в нужный трансопрт
#            App\Message\TechSupportRequestMessage: support_tech
#            App\Message\FinanceSupportRequestMessage: support_finance
#            App\Message\ManagementSupportRequestMessage: support_management
            App\Message\SupportRequestMessage: support_fanout
